//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinoEntities2 : DbContext
    {
        public KinoEntities2()
            : base("name=KinoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<afish> afish { get; set; }
        public virtual DbSet<kassir> kassir { get; set; }
        public virtual DbSet<otchot> otchot { get; set; }
        public virtual DbSet<seans> seans { get; set; }
        public virtual DbSet<snacks> snacks { get; set; }
        public virtual DbSet<zall> zall { get; set; }
    }
}
