//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class otchot
    {
        public int id { get; set; }
        public int countTicket { get; set; }
        public int sumTicketPrice { get; set; }
        public int sumProdPrice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
