//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class seans
    {
        public int id { get; set; }
        public int afish_id { get; set; }
        public int zall_id { get; set; }
        public string selectPlant { get; set; }
        public string time { get; set; }
        public int price { get; set; }
    }
}
